### ISSUE TITLE
Camera Display - GUI/Controller/Model

### ISSUE THREAD

**Issue by codeCollision4** [TheDeanLab/ASLM#24]
# General Info
Need the GUI to display images from the camera. This requires creating a controller and updating both the synthetic and base models for the Camera class. The below task list outlines some of the required tasks, benchmarks and optimizations needed to ensure proper and efficient functionality. Any comments on my process or logic is appreciated and welcome. I don't want to miss anything.

## Todo List
- [x] #25
- [x] #26
- [x] #27
- [x] #28
- [x] #29
- [x] #30

## Benchmarking
- [ ] Frame save time to disk (after its been pulled from buffer)
- [ ] Spool time(how fast does the camera offload frames to buffer)
- [ ] Pull time from buffer (how long does it take to get a frame from the buffer)
- [ ] Displaying frame time (how long does it take to display a frame to GUI)
- [ ] Display Frames Per Second

## Optimizations
- [ ] Pulling from buffer is faster than spooling to buffer
- [ ] Saving a frame is faster than or will always come before displaying frame
- [ ] Framerate of GUI display needs to be at least 24fps
